package com.juansefdz.ApiMedic.medico;

public enum Especialidad {
    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    GERIATRIA,
    GINECOLOGIA,
    HEMATOLOGIA,
    NEFROLOGIA,
    NEUMOLOGIA,
    NEUROLOGIA,
    OFTALMOLOGIA,
    ONCOLOGIA,
    OTORRINOLARINGOLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    REUMATOLOGIA,
    TRAUMATOLOGIA,
    UROLOGIA
}
