services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=AluraSeriesDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345



